# These are the 10 tags used for opportunity filtering
TAGS = [
    "Ideation",
    "Problem Validation",
    "Solution Design",
    "Product-Market Fit (PMF)",
    "Early Traction",
    "Growth Stage",
    "Scaling",
    "Exit Strategy",
    "Hackathons",
    "Workshops",
    "Networking Events",
    "Internships",
    "Startup Competitions",
    "Volunteering",
    "Conferences",
    "Meetups",
    "Mentorship Programs",
    "Accelerators",
    "Incubators",
    "Pitch Competitions",
    "Product Development",
    "UX/UI Design",
    "Engineering",
    "Pricing Strategy",
    "Revenue Models",
    "Customer Support",
    "Legal & Compliance",
    "Operations",
    "Customer Acquisition",
    "Content Marketing",
    "SEO",
    "Paid Ads (PPC)",
    "Social Media",
    "Email Marketing",
    "Viral Growth",
    "Community Building",
    "Sales Strategy",
    "B2B Sales",
    "B2C Sales",
    "Partnerships",
    "Negotiation Tactics",
    "Churn Reduction",
    "Bootstrapping",
    "Pre-Seed Funding",
    "Seed Funding",
    "Series A+",
    "VC Pitching",
    "Financial Planning",
    "Unit Economics",
    "Founder Mental Health",
    "Hiring",
    "Remote Teams",
    "Team Culture",
    "Leadership Skills",
    "Data Analytics",
    "AI/ML",
    "Tech Stack",
    "Cybersecurity",
    "SaaS",
    "E-commerce",
    "Hardware",
    "Web3"
] 